version: "3.4"

services:
  consul:
    image: consul
    container_name: consul
    restart: always
    environment:
      - CONSUL_BIND_INTERFACE=eth0
    ports:
      - 8500:8500
    networks:
      - project105-net

networks:
  project105-net:
    name: project105-net
    driver: bridge
    external: true
